---
abstract: 'A fast and easy way to integrate your apps with Facebook.'
author:
  - 'JT Smith <jt@plainblack.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.102340, CPAN::Meta::Converter version 2.101670'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Facebook-Graph
no_index:
  directory:
    - author.t
    - eg
requires:
  Any::Moose: 0.13
  Crypt::SSLeay: 0.57
  DateTime: 0.61
  DateTime::Format::Strptime: 1.4000
  Digest::SHA: 5.47
  Exception::Class: 1.32
  JSON: 2.16
  LWP: 5.836
  MIME::Base64::URLSafe: 0.01
  Test::More: 0
  URI: 1.54
  URI::Encode: 0.02
resources:
  bugtracker: http://github.com/rizen/Facebook-Graph/issues
  repository: git://github.com/rizen/Facebook-Graph.git
version: 1.0100
